#!/bin/bash
@echo off
echo Voce foi invadido hehehehe
echo Prepare-se para ver a introducao para os cursos de Orientação a Objetos Avançada
timeout /t 5 >null

start "" "https://www.youtube.com/watch?v=2654zH3bFKc"

